package simpledb.execution;

import simpledb.transaction.TransactionAbortedException;
import simpledb.common.DbException;
import simpledb.storage.Tuple;
import simpledb.storage.TupleDesc;

import java.util.*;

/**
 * The Join operator implements the relational join operation.
 */
public class Join extends Operator {

    private static final long serialVersionUID = 1L;

    private final JoinPredicate p;

    private OpIterator it1;

    private OpIterator it2;

    private Tuple t1;

    /**
     * Constructor. Accepts two children to join and the predicate to join them
     * on
     * 
     * @param p
     *            The predicate to use to join the children
     * @param child1
     *            Iterator for the left(outer) relation to join
     * @param child2
     *            Iterator for the right(inner) relation to join
     */
    public Join(JoinPredicate p, OpIterator child1, OpIterator child2) {
        // some code goes here
        this.p = p;
        this.it1 = child1;
        this.it2 = child2;
    }

    public JoinPredicate getJoinPredicate() {
        // some code goes here
        return this.p;
    }

    /**
     * @return
     *       the field name of join field1. Should be quantified by
     *       alias or table name.
     * */
    public String getJoinField1Name() {
        // some code goes here
        return it1.getTupleDesc().getFieldName(p.getField1());
    }

    /**
     * @return
     *       the field name of join field2. Should be quantified by
     *       alias or table name.
     * */
    public String getJoinField2Name() {
        // some code goes here
        return it2.getTupleDesc().getFieldName(p.getField2());
    }

    /**
     * @see TupleDesc#merge(TupleDesc, TupleDesc) for possible
     *      implementation logic.
     */
    public TupleDesc getTupleDesc() {
        // some code goes here
        TupleDesc tupleDesc = TupleDesc.merge(it1.getTupleDesc(), it2.getTupleDesc());
        return tupleDesc;
    }

    public void open() throws DbException, NoSuchElementException,
            TransactionAbortedException {
        // some code goes here
        it1.open();
        it2.open();
        super.open();
    }

    public void close() {
        // some code goes here
        super.close();
        it1.close();
        it2.close();
    }

    public void rewind() throws DbException, TransactionAbortedException {
        // some code goes here
        it1.rewind();
        it2.rewind();
    }

    /**
     * Returns the next tuple generated by the join, or null if there are no
     * more tuples. Logically, this is the next tuple in r1 cross r2 that
     * satisfies the join predicate. There are many possible implementations;
     * the simplest is a nested loops join.
     * <p>
     * Note that the tuples returned from this particular implementation of Join
     * are simply the concatenation of joining tuples from the left and right
     * relation. Therefore, if an equality predicate is used there will be two
     * copies of the join attribute in the results. (Removing such duplicate
     * columns can be done with an additional projection operator if needed.)
     * <p>
     * For example, if one tuple is {1,2,3} and the other tuple is {1,5,6},
     * joined on equality of the first column, then this returns {1,2,3,1,5,6}.
     * 
     * @return The next matching tuple.
     * @see JoinPredicate#filter
     */
    protected Tuple fetchNext() throws TransactionAbortedException, DbException {
        // some code goes here
        while(it1.hasNext() || t1 != null) {
            if(it1.hasNext() && t1 == null) {
                t1 = it1.next();
            }
            while(it2.hasNext()) {
                Tuple t2 = it2.next();
                if(p.filter(t1, t2)) {
                    TupleDesc td1 = t1.getTupleDesc();
                    TupleDesc td2 = t2.getTupleDesc();
                    TupleDesc td = TupleDesc.merge(td1, td2);
                    Tuple newTuple = new Tuple(td);
                    newTuple.setRecordId(t1.getRecordId());
                    for(int i = 0; i < td1.numFields(); i ++) {
                        newTuple.setField(i, t1.getField(i));
                    }
                    for(int i = 0; i < td2.numFields(); i ++) {
                        newTuple.setField(td1.numFields() + i, t2.getField(i));
                    }
                    if(!it2.hasNext()) {
                        it2.rewind();
                        t1 = null;
                    }
                    return newTuple;
                }
            }
            it2.rewind();
            t1 = null;
        }
        return null;
    }

    @Override
    public OpIterator[] getChildren() {
        // some code goes here
        return new OpIterator[]{it1, it2};
    }

    @Override
    public void setChildren(OpIterator[] children) {
        // some code goes here
        if(children == null || children.length < 2) return;
        it1 = children[1];
        it2 = children[2];
    }

}
